[package]
name = "zed_angular"
version = "0.0.1"
edition = "2021"
publish = false
license = "MIT"
authors = ["nathansbradshaw"]


[lib]
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.0.6"
