id = "angular"
name = "Angular"
description = "Angular Language support"
version = "0.0.1"
schema_version = 1
authors = ["nathansbradshaw"]
repository = "https://github.com/nathansbradshaw/zed-angular"
path_suffixes = ["html"]

[language_servers.vscode-angular-language-server]
name = "vscode-angular-language-server"
languages = ["Angular", "HTML", "TypeScript"]

[language_servers.vscode-angular-language-server.language_ids]
"HTML" = "html"
"TypeScript" = "typescript"
"Angular" = "angular"

[grammars.angular]
repository = "https://github.com/dlvandenberg/tree-sitter-angular"
commit = "c473dbc54ca27f95d8928cfdb2a1a79300e16951"
