id = "angular"
name = "Angular"
description = "Angular Language support"
version = "0.0.1"
schema_version = 1
authors = ["nathansbradshaw"]
repository = "https://github.com/nathansbradshaw/zed-angular"

[language_servers.angular]
name = "Angular Language Server"
languages = ["TypeScript", "HTML"]
language_ids = { "Angular" = "html" }

[grammars.angular]
repository = "https://github.com/dlvandenberg/tree-sitter-angular"
commit = "c473dbc54ca27f95d8928cfdb2a1a79300e16951"

[language_servers.vscode-angular-language-server]
language = "Angular"
